# Generated by Django 3.2.13 on 2022-04-18 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20220418_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, verbose_name='Activity')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity Location')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='requests',
            name='laptop_taxable_value',
        ),
        migrations.AddField(
            model_name='requests',
            name='dc_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='its_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='mailroom_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='taxable_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taxable Value'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='shipment_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipment Location'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='shipment_pickup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipment Pickup'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='activity',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organization.requests'),
        ),
    ]
